apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epydios-orchestration-runtime
rules:
  - apiGroups: ["controlplane.epydios.ai"]
    resources: ["extensionproviders", "extensionproviders/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
