apiVersion: v1
kind: Service
metadata:
  name: epydios-oss-evidence-provider
spec:
  selector:
    app.kubernetes.io/name: epydios-oss-evidence-provider
    app.kubernetes.io/component: provider
  ports:
    - name: http
      port: 8080
      targetPort: http

