apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: epydios-system
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - extensionprovider.yaml
labels:
  - pairs:
      app.kubernetes.io/name: oss-profile-static-resolver
      app.kubernetes.io/component: provider
      app.kubernetes.io/part-of: epydios-ai-control-plane
    includeSelectors: true
    includeTemplates: true
