apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: epydios-platform
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.55.0
    helm:
      releaseName: fluent-bit
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

