apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epydios-control-plane-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
spec:
  project: epydios-platform
  source:
    repoURL: https://github.com/Epydios/Epydios-AgentOps-Desktop.git
    targetRevision: main
    path: platform/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: epydios-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
