apiVersion: v1
kind: Service
metadata:
  name: extension-provider-registry-controller
spec:
  selector:
    app.kubernetes.io/name: extension-provider-registry-controller
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP

