apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../system
  - ../../providers/oss-policy-opa
  - ../../providers/oss-evidence-memory
  - ../../data/cnpg-prod-cluster
  - ../../hardening/networkpolicy
  - ../../hardening/monitoring
  - ../../hardening/admission
  - runtime-auth-config.yaml
  - runtime-httproute.yaml
  - networkpolicy-runtime-ingress.yaml
  - networkpolicy-runtime-egress.yaml
  - networkpolicy-provider-ingress.yaml
  - pdb-orchestration-runtime.yaml
  - pdb-extension-provider-registry-controller.yaml
  - servicemonitor-orchestration-runtime.yaml
  - prometheusrule-orchestration-runtime.yaml
patches:
  - path: patch-orchestration-runtime-deployment.yaml
  - path: patch-orchestration-runtime-service.yaml
  - path: patch-extension-provider-registry-controller-deployment.yaml
  - path: patch-namespace-epydios-system.yaml
  - path: patch-image-digests.yaml
