apiVersion: v1
kind: Namespace
metadata:
  name: epydios-system
  labels:
    app.kubernetes.io/part-of: epydios-ai-control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve

