apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: epydios-platform
  namespace: argocd
spec:
  description: Baseline platform add-ons for Epydios AgentOps Control Plane
  sourceRepos:
    - https://github.com/Epydios/Epydios-AgentOps-Desktop.git
    - ssh://git@github.com/Epydios/Epydios-AgentOps-Desktop.git
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://cloudnative-pg.github.io/charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://fluent.github.io/helm-charts
    - https://kedacore.github.io/charts
    - https://github.com/kubernetes-sigs/gateway-api.git
    - https://github.com/argoproj/argo-rollouts.git
    - https://github.com/argoproj/argo-events.git
    - https://github.com/kserve/kserve.git
    - https://ray-project.github.io/kuberay-helm
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
